---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes
  #remote_user: root

  roles:
    - common

- name: applay dnsmasq to nat 
  hosts: localenv
  sudo: yes

  roles:
    - dnsmasqserver 

- name: web01 configura 
  hosts: web
  sudo: yes

  roles: 
    - dnsmasqclient

- name: db01 configura
  hosts: web
  sudo: yes

  roles:
    - dnsmasqclient



#- name: configure and deploy the webservers and application code
#  hosts: webservers
#  remote_user: root
#
#  roles:
#    - web

#- name: deploy MySQL and configure the databases
#  hosts: dbservers
#  remote_user: root
#
#  roles:
#    - db
