---
# tasks file for docker

- sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes




- sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes


- name: ensure config folder is present
  file:
    path: /etc/docker
    state: directory

- name: ensure graph dirs is present
  file:
    path: /opt/docker_data
    state: directory

- name: ensure run shell dirs is present
  file:
    path: /opt/run
    state: directory

- name: install python-setuptools
  yum:
    name: python-setuptools
    state: latest

- easy_install:
    name: pip
    state: latest

- pip:
    name: docker-py

- name: Install Docker
  yum: 
    name: docker 
    state: latest

#- name: copy daemon.json 
#    template: src=daemon.json.j2 dest=/etc/docker/daemon.j2
#    tags: docker

- name: ensure unit file is present & up to date
  template:
    src: docker.service.j2
    dest: /usr/lib/systemd/system/docker.service
  notify:
    - reload unit
    - restart docker

- name: ensure daemon config file is present
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify:
    - restart docker


- service: 
    name: docker 
    state: started


- service:
    name: docker
    enabled: yes
